### ISSUE TITLE
历史消息阅读数和点赞数

### ISSUE THREAD

**Issue by BiterrorChen** [wnma3mz/wechat_articles_spider#1]
您好，请问现在可以爬取历史消息的阅读数和点赞数吗？

**Comment by wnma3mz** [comment]
现在已经可以了，目前还是需要手动设置cookie和appmsg_token

**Comment by BiterrorChen** [comment]
已经正确设置cookie和appmsg_token。
但是LoginWeChat.py：199行不能请求成功。

appmsgext_json = requests.post(appmsgext_url, headers=self.headers, data=self.data).json()

**Comment by BiterrorChen** [comment]
使用的mac系统

**Comment by wnma3mz** [comment]
不好意思，今天晚上修复的bug，可以重新pull一下
