### ISSUE TITLE
公众平台登录可以实现无人值守吗？

### ISSUE THREAD

**Issue by mingchau** [wnma3mz/wechat_articles_spider#10]
你好，我最近也在做一个类似的爬虫。
采取的思路和你的是一致的，通过登录一个自己的个人公众账号，获取到cookies和token之后，通过接口去获取某一个公众号的文章列表。

但是这个每次登录，都需要人工干预。我尝试把公众平台登录界面的二维码发送到手机，然后长按识别，这样不能达到想要的效果。

请问你这边有可以不需要人工盯着的登录方式吗？

**Comment by yaocharley** [comment]
没有更好的思路




在 2019-03-11 15:30:37，"mingchao" <notifications@github.com> 写道：


你好，我最近也在做一个类似的爬虫。
采取的思路和你的是一致的，通过登录一个自己的个人公众账号，获取到cookies和token之后，通过接口去获取某一个公众号的文章列表。

但是这个每次登录，都需要人工干预。我尝试把公众平台登录界面的二维码发送到手机，然后长按识别，这样不能达到想要的效果。

请问你这边有可以不需要人工盯着的登录方式吗？

**Comment by wnma3mz** [comment]
有一个想法，但是没实践过，大致思路是需要一台手机，电脑用adb连接。
用adb点击，理论上应该是可以实现自动的。
@mingchau

**Comment by mingchau** [comment]
@wnma3mz 
理论上是这样，但这样，还需要一台手机和电脑显示器保持固定的物理距离和相对位置。

实现起来还是比较麻烦，我已经暂时放弃这个想法了：）
