### ISSUE TITLE
怎么获取文章中图片的src呢？

### ISSUE THREAD

**Issue by llibetter** [wnma3mz/wechat_articles_spider#11]
您好，根据代码我已经拿到文章的url了。下一步想把文章存到word里，但是拿不到图片的src，咋解决呢。

**Comment by wnma3mz** [comment]
```python
# coding: utf8
import requests
import re

url = 'https://mp.weixin.qq.com/s?sn=6d1f0f51ae36291a4502608bcc38bd9b&__biz=MjM5NTUxNjQwMw==&mid=2651427109&idx=1&chksm=bd0a6bb98a7de2af1cdad90562a313e265782b4a58ae9907a5da3c0cd41df67b02c8c38b29c3&scene=21#wechat_redirect'
html = requests.get(url).text
src_lst = re.findall(r'src="(.+)"', html)
```
大概这样就可以提取出文章中所有src的链接，图片就包含在其中。
关于进一步过滤出图片的url及考虑图片的顺序，就需要进一步完善这个提取过程。
@llibetter

**Comment by llibetter** [comment]
> ```python
> # coding: utf8
> import requests
> import re
> 
> url = 'https://mp.weixin.qq.com/s?sn=6d1f0f51ae36291a4502608bcc38bd9b&__biz=MjM5NTUxNjQwMw==&mid=2651427109&idx=1&chksm=bd0a6bb98a7de2af1cdad90562a313e265782b4a58ae9907a5da3c0cd41df67b02c8c38b29c3&scene=21#wechat_redirect'
> html = requests.get(url).text
> src_lst = re.findall(r'src="(.+)"', html)
> ```
> 
> 大概这样就可以提取出文章中所有src的链接，图片就包含在其中。
> 关于进一步过滤出图片的url及考虑图片的顺序，就需要进一步完善这个提取过程。
> @llibetter

3q，原来文章里的图片是js加载上去的，用selenium模拟下滑操作，等加载完，再提取src。

**Comment by wnma3mz** [comment]
嗯嗯，用`requests`方便一点，也快一点。

**Comment by yaocharley** [comment]
不好意思，关于图片没有研究，你可以尝试一下正则表达式匹配




在 2019-03-14 20:57:31，"llibetter" <notifications@github.com> 写道：


您好，根据代码我已经拿到文章的url了。下一步想把文章存到word里，但是拿不到图片的src，咋解决呢。
