### ISSUE TITLE
关于公众号文章抓取速度与频率

### ISSUE THREAD

**Issue by zzmao** [wnma3mz/wechat_articles_spider#12]
@wnma3mz 你好，感谢你的code，非常clean，很喜欢！

在你的博客上看到说```从公众号获取永久链接时，间隔3分钟，可以连续获取几小时```
有三个问题：
1. 连续获取几小时后会发生什么？
2. 获取的文章链接，可以任意速率抓取吗？ 
3. 获取的文章的链接是永久 还是也有几小时限制?

**Comment by wnma3mz** [comment]
1. 连续使用这个方式获取链接几小时后，不能继续抓取。网页认定频繁，实际上，这个效果等同于在网页端频繁点击下一页，用不了多久就会有提示，大意是，操作频繁，请稍后再试
2. 获取到的文章链接是可以任意速率抓取的。但实际还是要看是抓取什么，阅读量/点赞数，还是评论。前者的话是建议有一个固定时长，大概3s左右就差不多，这样一个公众号（几百上千篇文章）应该是可以一次性抓取的，封锁机制是每个账号。评论数可以间隔稍短，他的主要封锁机制是ip。
3. 获取到的链接是永久链接

**Comment by yaocharley** [comment]
回答不也，不好意思
刚学



At 2019-05-18 05:23:57, "Ze Mao" <notifications@github.com> wrote:


@wnma3mz 你好，感谢你的code，非常clean，很喜欢！

在你的博客上看到说从公众号获取永久链接时，间隔3分钟，可以连续获取几小时
有两个问题：

连续获取几小时后会发生什么？
获取的文章链接，可以任意速率抓取吗？

**Comment by zzmao** [comment]
@wnma3mz 
我在你的code基础上进行了公众号搜索，想根据关键字检索出所有公众号。
但是发现，每request 10次(count=5) 就会遇到一次freq control. 即使中间间隔5s。


我也试了一下给定公众号名字，也是reqest 10次会遇到一个freq control。 

所以看起来10次request 是微信的一个限制。 

但是 如果request之间相隔3分钟，这也太慢了吧？

**Comment by wnma3mz** [comment]
是的，所以在这个项目里还有一种方法。根据历史消息来获取。。没有说明具体操作。可参考readme中的说明

**Comment by wnma3mz** [comment]
@zzmao https://github.com/wnma3mz/wechat_articles_spider/blob/master/wechatarticles/GetUrls.py。源码见这个文件

**Comment by zzmao** [comment]
好的！我试一下。 
确认一下:
uin: str `用户id`
key: str `个人微信号登陆后获取的key`
都是通过fiddler获取的吧?

**Comment by wnma3mz** [comment]
是的

**Comment by zzmao** [comment]
我还看到你在用中间人攻击的方式获取以下的值.
```
# 支持自动获取appmsg_token和cookie
appmsg_token, cookie = Reader().contral(outfile)
```
这个outfile怎么生成呢？

**Comment by wnma3mz** [comment]
根据mitmproxy（python的第三方包）来获取的
