### ISSUE TITLE
楼主你好，可以加您微信交流下嘛

### ISSUE THREAD

**Issue by xhochipe** [wnma3mz/wechat_articles_spider#14]
你好楼主，非常感谢您写的项目，可以加微信交流下嘛，谢谢

**Comment by wnma3mz** [comment]
请看博客，博客末尾有联系方式。[微信公众号爬虫](http://blog.csdn.net/wnma3mz/article/details/78570580)

**Comment by xhochipe** [comment]
好的，谢谢啦，已经加您了，我关issue
