### ISSUE TITLE
mitmdump 无法有效解析微信 PC 版数据

### ISSUE THREAD

**Issue by amitbha** [wnma3mz/wechat_articles_spider#15]
微信PC安装在xp上，并在登录界面设了代理，指向 mitmdump 的 ip 和端口；mitmdump 在另一台机器上运行
在 xp 上导入 mitmdump 生成的证书
在 xp 上运行并登录微信，mitmdump 打印大量的错误信息，比如：
```
192.168.10.102:1869: CONNECT 113.96.209.105:443
 << HTTP protocol error in client request: Bad HTTP request line: b'\x16\xf1\x03\x00\xa1\x00\x00 .....
192.168.10.102:1863: CONNECT 14.17.73.39:80
 << HTTP protocol error in client request: Bad HTTP request line: b"\xab\x00\x00\x01\x03'\ ....
```
一直找不到发向 `mp.weixin.qq.com/mp/` 的流量。会是证书的问题吗？
在 xp 上运行 fiddler，抓取是正常的

**Comment by wnma3mz** [comment]
未在xp的机器上运行过，不过看报错，确实有可能是证书的问题。fiddler是否有安装ssl证书？如果fiddler也没有安装ssl证书的话，也有可能是mitmdump的问题。[@amitbha](https://github.com/amitbha)

**Comment by amitbha** [comment]
> 未在xp的机器上运行过，不过看报错，确实有可能是证书的问题。fiddler是否有安装ssl证书？如果fiddler也没有安装ssl证书的话，也有可能是mitmdump的问题。[@amitbha](https://github.com/amitbha)

fiddler 遇到加密流量会提示，按提示操作就装好证书了，用起来确实方便，但好像不能用来编程啊
换了台win7的机器，还是一样的情况

操作上有什么问题？
mitmdump运行后会生成证书，把其中的 mitmproxy-ca-cert.p12 拷贝到 xp 上，双击导入，导入位置选的是根域可信任。
用浏览器试了一下，访问 https 站点都抓取正常，微信PC就有问题

**Comment by wnma3mz** [comment]
> > 未在xp的机器上运行过，不过看报错，确实有可能是证书的问题。fiddler是否有安装ssl证书？如果fiddler也没有安装ssl证书的话，也有可能是mitmdump的问题。[@amitbha](https://github.com/amitbha)
> 
> fiddler 遇到加密流量会提示，按提示操作就装好证书了，用起来确实方便，但好像不能用来编程啊
> 换了台win7的机器，还是一样的情况
> 
> 操作上有什么问题？
> mitmdump运行后会生成证书，把其中的 mitmproxy-ca-cert.p12 拷贝到 xp 上，双击导入，导入位置选的是根域可信任。
> 用浏览器试了一下，访问 https 站点都抓取正常，微信PC就有问题

1. fiddler可以进行二次开发的，需要用JS
2. mitmproxy的话，可能确实是因为它有这个问题，具体不是很了解
