### ISSUE TITLE
appmsg_token用同一个微信号阅读不同微信公众号的文章时似乎值不一样

### ISSUE THREAD

**Issue by sunshin5** [wnma3mz/wechat_articles_spider#16]
appmsg_token用同一个微信号阅读不同微信公众号的文章时似乎值不一样，有办法自动获取吗？半天内就失效？如果我想用一个微信号看100个微信公众号文章的阅读数似乎做不到

**Comment by wnma3mz** [comment]
@sunshin5 
1. 不同微信公众号的appmsg_token确实不一样，目前没有自动获取。失效时间未测试。
2. 不是很明白。一个微信号看100个不同公众号的文章，前提是需要关注才能获取。

综上，需要两个自动步骤，自动获取appmsg_token，批量关注100个公众号。
1. 自动获取的话，只能用定时刷新请求，这里可以用控制手机（比如adb）结合mitmproxy或者其他的抓包工具。
2. 暂时未有好的解决方案
