### ISSUE TITLE
请问在pycharm中run或者debug会不断出现登陆的二维码，如何解决呢

### ISSUE THREAD

**Issue by LxinG-YY** [wnma3mz/wechat_articles_spider#17]
尝试在pycharm中进行debug的时候，二维码会不断出现，扫描登陆了也没办法继续下去，不知道大家有没有好的解决方法呢，感谢！

**Comment by wnma3mz** [comment]
不使用二维码登陆，使用cookie登陆

**Comment by Guxulong** [comment]
> 不使用二维码登陆，使用的cookie登陆

cookie你是手动添加的还是怎么搞得呢？？

**Comment by wnma3mz** [comment]
> > 不使用二维码登陆，使用的cookie登陆
> 
> cookie你是手动添加的还是怎么搞得呢？？

手动

**Comment by Guxulong** [comment]
ok 谢谢 我现在在使用selenium模拟登录获取cookie信息和token
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"wnma"<notifications@github.com&gt;;
 发送时间:&nbsp;2019年9月19日(星期四) 下午3:34
 收件人:&nbsp;"wnma3mz/wechat_articles_spider"<wechat_articles_spider@noreply.github.com&gt;;
 抄送:&nbsp;"TT"<1059044764@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
 主题:&nbsp;Re: [wnma3mz/wechat_articles_spider] 请问在pycharm中run或者debug会不断出现登陆的二维码，如何解决呢 (#17)

 

   
不使用二维码登陆，使用的cookie登陆
 
cookie你是手动添加的还是怎么搞得呢？？
 
手动

**Comment by nimozzzz** [comment]
抓包人微信的cookies的地址变成了这个
GET /mp/jsmonitor?idkey=65080_31_1&t=0.311059175213525 HTTP/1.1

怎么弄都不对，求指导

**Comment by wnma3mz** [comment]
> 抓包人微信的cookies的地址变成了这个
> GET /mp/jsmonitor?idkey=65080_31_1&t=0.311059175213525 HTTP/1.1
> 
> 怎么弄都不对，求指导

你说的是微信PC端的吗？我刚刚看了一下，没有变哈，你找错了url应该，或者你没有配置对Fiddler（或是其他抓包工具）。具体查看cookie方法见博客。

**Comment by nimozzzz** [comment]
@wnma3mz 感谢回复
我使用了所有的方式，均是在获取appmsg_token和wechat_cookie，希望您能指导
1.手动获取这两个指标，博客链接（https://github.com/wnma3mz/wechat_articles_spider/blob/master/docs/get_appmsg_token.md）是获取点赞数和评论数的教程。

2.按照获取赞数和评论数的教程。我尝试使用fiddler获取appmsg_token和wechat_cookie，配置后fiddler已经可以获取手机微信的数据，但是没有找到博主教程内的url地址，我换了多台电脑配置，均无法找到，具体下图
![1](https://user-images.githubusercontent.com/41815560/68188431-131ffa80-ffe4-11e9-8a77-1df0ec4da2ba.png)

3.尝试自动获取appmsg_token和wechat_cookie，找不到outfile文件，感觉应该和第2点是同一个原因导致的，运行代码如下图
![2](https://user-images.githubusercontent.com/41815560/68188518-4c586a80-ffe4-11e9-92c3-bb4091034e06.png)

**Comment by wnma3mz** [comment]
图中有cookie这种隐私信息，已删除。首先我得承认我确实没有遇到过你这种问题，并且按照图中显示确实获取到了https这种url。

按照你所说，换了电脑配置也无法找到。所以我有以下建议，希望能对你有所帮助。

1. 这个微信号本身是否存在一些问题？被微信官方作了限制？

2. 在拿这token和cookie的时候，需要打开某篇微信公众号的文章才能显示出url

3. 最后一点分析的原因应该是没错的。不知你是否对微信的手机端和PC端都做了尝试？

**Comment by nimozzzz** [comment]
昨天晚上再次研究了一下，找到了问题的所在。
不出意外应该是手机系统的问题。我昨晚尝试通过安卓机器使用fiddler可以抓包到和博主一样的信息。
另外发现了一些注意事项，Android7以上，和微信7以上对抓包有多处限制，具体参考这篇博客https://aoye8.com/detail/1143.html，这边博客写作时间有些上了，目前ios应该已经不能用了(因为我之前就是用的ios)

**Comment by wnma3mz** [comment]
> 昨天晚上再次研究了一下，找到了问题的所在。
> 不出意外应该是手机系统的问题。我昨晚尝试通过安卓机器使用fiddler可以抓包到和博主一样的信息。另外发现了一些注意事项，Android7以上，和微信7以上对抓包有多处限制，具体参考这篇博客https://aoye8.com/detail/1143.html
> 这边博客写作时间有长了，目前ios应该已经不能用了(因为我之前就是用的ios)

推荐用pc端微信哈。另刚刚测试ios还可以抓到。
系统版本13.2，微信版本7.0.8。用手机上的软件stream即可

**Comment by nimozzzz** [comment]
再次感谢博主指导，电脑端微信已抓包成功，并且还成功抓包小程序。

但是我在ios上使用软件stream，没有成功，我还是只能获取GET /mp/jsmonitor?idkey...的连接
目前还有一个问题困扰着我，希望博主能为我解惑。目前我通过fiddler端抓包数据想获得如：json文件文件中的内容，目前只能通过手动存储到本地，再使用python open()方法在本地读取。

问题1.所以是否存在fiddler端和python端数据互相传输的方式？是通过mitmproxy模块吗？

**Comment by wnma3mz** [comment]
> 再次感谢博主指导，电脑端微信已抓包成功，并且还成功抓包小程序。
> 
> 但是我在ios上使用软件stream，没有成功，我还是只能获取GET /mp/jsmonitor?idkey...的连接
> 目前还有一个问题困扰着我，希望博主能为我解惑。目前我通过fiddler端抓包数据想获得如：json文件文件中的内容，目前只能通过手动存储到本地，再使用python open()方法在本地读取。
> 
> 问题1.所以是否存在fiddler端和python端数据互相传输的方式？是通过mitmproxy模块吗？

使用stream时，是否安装了证书？如果安装了的话，我只能认为是微信账号的问题了。如果是希望通过fiddler的话，可以搜索“fiddler js插件”这种，推荐查询fiddler的官方文档，当然也可以用python写插件。

mitmproxy的作用就是fiddler，所以如果用了mitmproxy就可以直接用python写插件，如我在[ReadOutfile.py](https://github.com/wnma3mz/wechat_articles_spider/blob/master/wechatarticles/ReadOutfile.py)写的简单demo一样，更多例子请查阅mitmproxy文档。
