### ISSUE TITLE
mitmdump: command not found

### ISSUE THREAD

**Issue by EverydayLearning** [wnma3mz/wechat_articles_spider#18]
你好，请问：
通过os模块执行 mitmdump命令时 提示找不到，使用subprocess模块发现也无法找到mitmdump，有什么办法能够解决的吗

**Comment by wnma3mz** [comment]
@EverydayLearning 
README中有说明[这篇文档](https://github.com/wnma3mz/wechat_articles_spider/blob/master/docs/%E5%85%B3%E4%BA%8E%E8%87%AA%E5%8A%A8%E8%8E%B7%E5%8F%96%E5%BE%AE%E4%BF%A1%E5%8F%82%E6%95%B0.md)有介绍，如有疑惑请阅读完文档再进行提问

**Comment by EverydayLearning** [comment]
> @EverydayLearning
> README中有说明[这篇文档](https://github.com/wnma3mz/wechat_articles_spider/blob/master/docs/%E5%85%B3%E4%BA%8E%E8%87%AA%E5%8A%A8%E8%8E%B7%E5%8F%96%E5%BE%AE%E4%BF%A1%E5%8F%82%E6%95%B0.md)有介绍，如有疑惑请阅读完文档再进行提问

你好，是每次执行到`os.system(command)`的时候会报错，提示`mitmdump command not found`
![image](https://user-images.githubusercontent.com/35058785/66745998-2216ff80-eeb3-11e9-9ab0-180d5b571e06.png)

**Comment by wnma3mz** [comment]
第一，我不清楚你是否安装了`mitmdump`；第二，你的运行环境是什么？(Windows？Ubunut？）

如果已安装，请试着添加`mitmdump`至系统的环境变量。

这个报错应该是指已安装`mitmdump`在`Python`的3.6.4版本中，但是我同时又看到你似乎有一个`pyenv`虚拟运行环境，这个虚拟环境是否有`mitmdump`？

**Comment by EverydayLearning** [comment]
环境是macOS10.14.3
我在命令行下运行mitmdumps是有效果的， 但是在代码中运行有问题
![image](https://user-images.githubusercontent.com/35058785/66746438-6bb41a00-eeb4-11e9-8d6a-1bfce430a494.png)

**Comment by wnma3mz** [comment]
> 环境是macOS10.14.3
> 我在命令行下运行mitmdumps是有效果的， 但是在代码中运行有问题
> ![image](https://user-images.githubusercontent.com/35058785/66746438-6bb41a00-eeb4-11e9-8d6a-1bfce430a494.png)

那你运行代码是否是在一个Python的虚拟环境中？

**Comment by EverydayLearning** [comment]
是的  我通过pyenv创建的3.6.4环境  终端也是3.6.4的环境 都是在同一个环境下运行的

**Comment by wnma3mz** [comment]
这个虚拟环境是否具备`mitmdump`？在虚拟环境中执行命令`pip list | grep mitmdump` 查看虚拟环境中是否有这个库

**Comment by wnma3mz** [comment]
另外，如果你既然在默认的Python中有`mitmdump`，不妨直接将代码运行在默认版本的Python中，不使用虚拟环境。

**Comment by EverydayLearning** [comment]
谢谢解答，我的虚拟环境和默认环境都带有mitmdump，具体为什么通过os执行不了我再找找

**Comment by wnma3mz** [comment]
1. 试试在默认环境运行？
2. 这里https://github.com/wnma3mz/wechat_articles_spider/blob/bdb28ad7f6b6e8f492ac519456ad35f6accf5d43/wechatarticles/ReadOutfile.py#L126
`command`参数中的`mitmdump`使用绝对路径，很抱歉这里我当时直接忽略了这点

**Comment by EverydayLearning** [comment]
你好，问题应该是我使用pyenv出现的问题，在没有使用pyenv的环境下 通过`os.system（’mitmdump‘）`可以执行。
再请教一个问题，我手动输入appmsg_token 等参数，再获取文章的阅读数时返回的是空，获取的文章链接是成功的。
![image](https://user-images.githubusercontent.com/35058785/66811895-7928dd00-ef64-11e9-904b-be7df0428a04.png)
返回的评论等信息
![image](https://user-images.githubusercontent.com/35058785/66812039-b8572e00-ef64-11e9-87c9-77d283be232a.png)
通过charles抓包 并修改请求 我发现携带的参数只有这四个是不可以的(也有可能是我操作有问题)，请教一下

**Comment by wnma3mz** [comment]
这里应该是先设定好了`appmsg_token`等参数再运行吧？
我不明白你的意思，什么叫做这四个是不可以？（不可以什么？）

P.S. 请检查参数是否输入正确，正常打开文章是否可以看到阅读点赞评论？（用手机或者电脑打开微信文章）

**Comment by EverydayLearning** [comment]
> 这里应该是先设定好了`appmsg_token`等参数再运行吧？
> 我不明白你的意思，什么叫做这四个是不可以？（不可以什么？，哪四个参数？）
> 
> P.S. 请检查参数是否输入正确，正常打开文章是否可以看到阅读点赞评论？（用手机或者电脑打开微信文章）

我是通过抓包手动输入了 official_cookie，token，appmsg_token，wechat_cookie。可以获取到文章链接 说明公众号那步没有问题，在获取文章评论点赞数的时候 data里的四个参数，好像不够
![image](https://user-images.githubusercontent.com/35058785/66813140-d2920b80-ef66-11e9-983f-72acaf840cd9.png)
就比如 我有`is_only_read`这个参数返回的时候是这样
![image](https://user-images.githubusercontent.com/35058785/66813466-5fd56000-ef67-11e9-9533-8c5341b2d63a.png)
当我删除了这个参数的时候：
![image](https://user-images.githubusercontent.com/35058785/66813523-7f6c8880-ef67-11e9-8a87-1aeddaf8054c.png)

**Comment by wnma3mz** [comment]
我在这里有加这个参数的，不知道你是如何运行的？

https://github.com/wnma3mz/wechat_articles_spider/blob/bdb28ad7f6b6e8f492ac519456ad35f6accf5d43/wechatarticles/ArticlesInfo.py#L34-L38

或者你可以参考[test_WechatInfo.py](https://github.com/wnma3mz/wechat_articles_spider/blob/master/test/test_WechatInfo.py)文件写法

**Comment by EverydayLearning** [comment]
十分感谢你的解答！
我确认一下，我的`appmsg_token`和`cookie` 是在点击任意的文章 通过抓包获取的这个链接中获取的
`https://mp.weixin.qq.com/mp/getappmsgext?f=json&mock=&uin=MjQzNDA4MzUzNA%253D%253D&key=5e4f3af4a46b6399d93089c9b5ef11bcea9b976bb48e40515b8fb04ab31da7aa6a4badb361100a64579ef9015f8e5d17976ec05711b63756bd363f18b1d93cd3b8ba5ac20a12638fde306c6197dba0dd&pass_ticket=ciXQi481WPW5IFarTHS3Fi9kwGrRVnMn6V6uo0%25252BJ0ewxXjBVMtrcoMvjaLLhOJIm&wxtoken=777&devicetype=iMac%26nbsp%3BMacBookPro12%2C1%26nbsp%3BOSX%26nbsp%3BOSX%26nbsp%3B10.14.3%26nbsp%3Bbuild(18D109)&clientversion=12031b12&__biz=MjM5Njc0MjIwMA%3D%3D&appmsg_token=1030_mNcFPeAFQzGOfdLt6fUEqnGoNQbsI4X0S6FA4YZoC_20WM612kC1gpWfr4fdjAK5N_RdDfOJ9PBoXOI6&x5=0&f=json`
再次感谢热心作者了

**Comment by wnma3mz** [comment]
是的，为防止你的key被他人利用，我将删除你的此条评论

**Comment by EverydayLearning** [comment]
大佬，我又来问问题了，经过多次抓包，手动传入`appmsg_token,cookie` 访问`getappmsgext`接口返回的信息还是为空。
![image](https://user-images.githubusercontent.com/35058785/66900868-29174c80-f030-11e9-9576-3a98f9e37ec2.png)
于是我使用自动获取appmsg_token和cookie的方式
![image](https://user-images.githubusercontent.com/35058785/66901026-78f61380-f030-11e9-9c3c-e685e69c69d1.png)
command是要通过`os.system`执行的命令，但是他抛出了这个错误，于是我就把`outfile`替换为下面这种
![image](https://user-images.githubusercontent.com/35058785/66901175-c5d9ea00-f030-11e9-866c-af418da33f2c.png)
麻烦大佬了

**Comment by EverydayLearning** [comment]
> 大佬，我又来问问题了，经过多次抓包，手动传入`appmsg_token,cookie` 访问`getappmsgext`接口返回的信息还是为空。
> ![image](https://user-images.githubusercontent.com/35058785/66900868-29174c80-f030-11e9-9576-3a98f9e37ec2.png)
> 于是我使用自动获取appmsg_token和cookie的方式
> ![image](https://user-images.githubusercontent.com/35058785/66901026-78f61380-f030-11e9-9c3c-e685e69c69d1.png)
> command是要通过`os.system`执行的命令，但是他抛出了这个错误，于是我就把`outfile`替换为下面这种
> ![image](https://user-images.githubusercontent.com/35058785/66901175-c5d9ea00-f030-11e9-866c-af418da33f2c.png)
> 麻烦大佬了

替换成`path`路径 还是一样的错误
![image](https://user-images.githubusercontent.com/35058785/66901328-12252a00-f031-11e9-854b-70a13be62dbe.png)

**Comment by EverydayLearning** [comment]
> > 大佬，我又来问问题了，经过多次抓包，手动传入`appmsg_token,cookie` 访问`getappmsgext`接口返回的信息还是为空。
> > ![image](https://user-images.githubusercontent.com/35058785/66900868-29174c80-f030-11e9-9576-3a98f9e37ec2.png)
> > 于是我使用自动获取appmsg_token和cookie的方式
> > ![image](https://user-images.githubusercontent.com/35058785/66901026-78f61380-f030-11e9-9c3c-e685e69c69d1.png)
> > command是要通过`os.system`执行的命令，但是他抛出了这个错误，于是我就把`outfile`替换为下面这种
> > ![image](https://user-images.githubusercontent.com/35058785/66901175-c5d9ea00-f030-11e9-866c-af418da33f2c.png)
> > 麻烦大佬了
> 
> 替换成`path`路径 还是一样的错误
> ![image](https://user-images.githubusercontent.com/35058785/66901328-12252a00-f031-11e9-854b-70a13be62dbe.png)

找到原因了，是pyenv的问题，打扰了 但是手动输入appmsg_token和cookie还是返回的还是不行，作者有空的时候可以试试 接口是否失效了吗

**Comment by wnma3mz** [comment]
你用这个文件[test_WechatInfo.py](https://github.com/wnma3mz/wechat_articles_spider/blob/master/test/test_WechatInfo.py)试过吗？`appmsg_token`和`cookie`都是最新的吗？

不是接口的问题。如果是接口的问题，使用`mitmdump`也抓不到，二者都是一样的接口
