### ISSUE TITLE
关于qrcode_url中rd参数值的问题？

### ISSUE THREAD

**Issue by ljsun** [wnma3mz/wechat_articles_spider#2]
您好，最新我也在研究微信公众号爬取的问题，正好看到了您的项目。有一个问题还想请教下您：
　　获取二维码的url中每次会有一个rd参数，每次是不一样的，在您的项目中，我看您是把rd参数写死了。我找了很久rd参数的来源，感觉应该是某个js文件执行的结果，但是并没有找到，请问您研究过这个rd参数吗？

**Comment by wnma3mz** [comment]
不好意思。没有研究过。。我确实是写死了。不知道rd参数会有什么影响。如果有什么发现，欢迎一起讨论交流

**Comment by wnma3mz** [comment]
我测试自己登陆的时候，每次是可以正常登陆的

**Comment by ljsun** [comment]
不好意思，想请教下您另一个问题。在请求微信公众平台的https请求时，会不会经常出现没有相应的情况，就是程序卡在那里了。。一直没有响应请求

**Comment by ljsun** [comment]
比如，我现在获取到了一篇文章的链接，如https://mp.weixin.qq.com/s?__biz=MjM5MzExMjcyMA==&mid=2665516080&idx=1&sn=911a149eaf57f82f432f96776c959b5c&chksm=bd8fdbcf8af852d953be4e70e070128234d9cae9b1c8c1edeeeb86bb1ccedda2e0337e07216f&scene=21#wechat_redirect
我在浏览器中能直接打开这个页面（在清除了cookie的情况下），但是用requests请求就是一直无响应，我尝试把ssl证书导出来，但是openssl报错了。。。请问您具体遇到这种情况吗？

**Comment by wnma3mz** [comment]
一直无响应？指的是卡死吗？。正常情况下是不会有这种问题的啊。请问是指直接用requests.get这个url吗?
给出几种可能：
1. 网络状态不佳
2. 用了网络代理工具（比如Fillder、Charles），代理工具没有配置ssl。（SS服务也可能算在其中）
解决方案：
1. 多尝试几个网络（Wifi）
2. 关闭代理工具（比较简单）或者配置代理工具的ssl（稍微麻烦一点)

**Comment by ljsun** [comment]
您好，我又测试了几次，应该是网络的问题。感谢您的回答

**Comment by wnma3mz** [comment]
不客气，那我就关闭这个issue了。。。
