### ISSUE TITLE
关于获取公众号信息只能部分成功的疑问？

### ISSUE THREAD

**Issue by nimozzzz** [wnma3mz/wechat_articles_spider#20]
博主您好，我之前通过您提供的方式成功获取了小程序的信息，目前尝试获取公众号的信息部分成功。尝试获取了一些可以成功（如：人民网），但是有一些不能成功（如：养身之道，风水与养生）

具体报错方式如下图：
![TIM截图20191204142347](https://user-images.githubusercontent.com/41815560/70118399-d27ad600-16a2-11ea-8791-636832228a7b.png)

我使用的方式如图，是全手动获取，代码如下图（已删除cookies信息）
![TIM截图20191204142549](https://user-images.githubusercontent.com/41815560/70118546-36050380-16a3-11ea-9686-1427c9338743.png)

猜测失败原因有2个可能：
1.是否和公众号的类型有关，如企业号和订阅号有关系
2.目前获取是通过微信公众号的后台查询获取，我手动查询后发现有重名
![TIM截图20191204143553](https://user-images.githubusercontent.com/41815560/70118723-aad83d80-16a3-11ea-8411-d4fd662597bb.png)

望答复...

**Comment by wnma3mz** [comment]
你好，失败的原因应该不是重名的关系。因为我的只返回了查询结果的第一个，所以最多查错，但不会因为这个报错。关于订阅号类型的原因，还未测试。

请问是否是查询太频繁，导致了短期内查询失败？

推荐使用第二种方法获取url，根据个人微信号来搜索url，[test_GetUrls.py](https://github.com/wnma3mz/wechat_articles_spider/blob/master/test/test_GetUrls.py)

**Comment by nimozzzz** [comment]
应该不是查询频繁导致失败的，我的操作是第一次爬虫"风水与养生"失败，再次爬虫"人民网"成功。
目前正在尝试test_GetUrls.py方法。
