### ISSUE TITLE
通过微信公众平台查看文章url的方法已经失效了，大佬应该怎么解决？

### ISSUE THREAD

**Issue by Guanyu1** [wnma3mz/wechat_articles_spider#23]
没有查找文章的按钮了

**Comment by wnma3mz** [comment]
1. 我这边看的还可以
![image](https://user-images.githubusercontent.com/23001152/81368838-6570de00-9123-11ea-837f-a9c09f73eb81.png)
2. 你可以试试pc端的历史文章
