### ISSUE TITLE
求问这个方法能大批量爬多公众号历史阅读数点赞数吗

### ISSUE THREAD

**Issue by xzchen555** [wnma3mz/wechat_articles_spider#26]
如题.

**Comment by wnma3mz** [comment]
我只能说可以在这上面拓展来实现，但是这个软硬件成本就需要额外计算了

**Comment by xzchen555** [comment]
> 我只能说可以在这上面拓展来实现，但是这个软硬件成本就需要额外计算了。换句话说，可以参考单个公众号获取的思路，具体拓展成多个公众号的需要额外开发：）

好的，谢谢。还有一个新的避免手动获取appmsg_token和pass_token的方法，可以将fiddler二次开发，直接将加密参数保存到本地。

**Comment by wnma3mz** [comment]
> > 我只能说可以在这上面拓展来实现，但是这个软硬件成本就需要额外计算了。换句话说，可以参考单个公众号获取的思路，具体拓展成多个公众号的需要额外开发：）
> 
> 好的，谢谢。还有一个新的避免手动获取appmsg_token和pass_token的方法，可以将fiddler二次开发，直接将加密参数保存到本地。

可以的，但这样不方便多个账号同时获取；且不支持服务器操作；且容易出现问题
