### ISSUE TITLE
在获取不同公众号文章时，上一个的个人token和cookie失效，有解决方案吗 

### ISSUE THREAD

**Issue by jomeswang** [wnma3mz/wechat_articles_spider#27]
在获取不同公众号文章时，使用上一个的token和cookie失效，但爬上一个的公众号文章时可以使用。
![image](https://user-images.githubusercontent.com/56079587/81800673-c5152200-9545-11ea-840b-37fe8d1e4fb0.png)

**Comment by wnma3mz** [comment]
暂无
