### ISSUE TITLE
获取文章阅读量和点赞量的接口失效了?

### ISSUE THREAD

**Issue by HananiJia** [wnma3mz/wechat_articles_spider#29]
![image](https://user-images.githubusercontent.com/31822623/82581287-ee2b5780-9bc2-11ea-91bf-5a165cd07498.png)
返回的appmsgext_json没有了appmsgstat

**Comment by wnma3mz** [comment]
麻烦发下微信文章链接，或者公众号

**Comment by HananiJia** [comment]
"link": "http://mp.weixin.qq.com/s?__biz=MzAxMzgyOTcyMw==&mid=2651273332&idx=1&sn=a8ba744b84717276c2821c90bdfe1af2&chksm=806f0b40b7188256eaf184e39043ff75baed9b1d5c93fbb927e69cfba480f251a44cd972382a#rd"
爬取了很多,发现都不可用,可以试试丁香医生这个公众号,看起来像是url加了chksm这个参数,而不是sm了

**Comment by wnma3mz** [comment]
每换一个公众号cookie和token需要更新一次。我这边测试正常

**Comment by HananiJia** [comment]
我也替换了啊,这里的cookie和token是说从微信客户端抓取的吧..不是开放平台的

**Comment by wnma3mz** [comment]
嗯呢

**Comment by wnma3mz** [comment]
是从这个地址复制的哈。。`https://mp.weixin.qq.com/mp/getappmsgext?`

**Comment by wnma3mz** [comment]
> chksm

接这条，这边就是正常获取了chksm和sn哈。没有sm。。

**Comment by wnma3mz** [comment]
> "link": "http://mp.weixin.qq.com/s?__biz=MzAxMzgyOTcyMw==&mid=2651273332&idx=1&sn=a8ba744b84717276c2821c90bdfe1af2&chksm=806f0b40b7188256eaf184e39043ff75baed9b1d5c93fbb927e69cfba480f251a44cd972382a#rd"
> 爬取了很多,发现都不可用,可以试试丁香医生这个公众号,看起来像是url加了chksm这个参数,而不是sm了

接这条，这边就是正常获取了chksm和sn哈。没有sm。。

**Comment by wnma3mz** [comment]
1. 你直接从客户端打开看看能不能获取阅读点赞。。
2. 是否关注了公众号？
3.  重新检查各个地方
4. 换个微信号
5. 我自己刚刚测试的平台是最新的微信PC客户端。

**Comment by HananiJia** [comment]
..我这边找到问题了抓取微信客户端cookie的时候cookie出了问题,我是直接在fiddler中cookie里边复制出来的.没有从headers里边复制出来,导致参数里边没有分号..不知道有没有表达清楚,感谢大佬指点.问题解决了

**Comment by wnma3mz** [comment]
get
