### ISSUE TITLE
请问这个会有token过期的问题吗？

### ISSUE THREAD

**Issue by paulwang2012** [wnma3mz/wechat_articles_spider#30]
我目前的项目用selenium模拟+扫码登录，大约20小时左右会出现
{"base_resp":{"ret":200003,"err_msg":"invalid session"}}

就得重新扫码登录公众号了

**Comment by wnma3mz** [comment]
> 我目前的项目用selenium模拟+扫码登录，大约20小时左右会出现
> {"base_resp":{"ret":200003,"err_msg":"invalid session"}}
> 
> 就得重新扫码登录公众号了

对的，是这样

**Comment by paulwang2012** [comment]
能否攻克这个难题，不然得每天手动登录一次
或者有其他方式，读取公众号的推送文章？

**Comment by wnma3mz** [comment]
> 能否攻克这个难题，不然得每天手动登录一次
> 或者有其他方式，读取公众号的推送文章？

无，如果有的话，我要么早就公开，要么就商用了
