### ISSUE TITLE
无法获得getappmsgext?返回的信息

### ISSUE THREAD

**Issue by xinghe98** [wnma3mz/wechat_articles_spider#33]
pc端已登陆微信但抓包getappmsgext?返回的json均为空值，appmsg_token也是空值
![image](https://user-images.githubusercontent.com/47097088/93964008-1b665d00-fd91-11ea-88e0-2ba23f9c8c3b.png)

**Comment by wnma3mz** [comment]
请使用微信自带的浏览器

**Comment by xinghe98** [comment]
谢谢，已解决
