### ISSUE TITLE
多次尝试后一直提示please update your key

### ISSUE THREAD

**Issue by xinghe98** [wnma3mz/wechat_articles_spider#34]
之前测试使用的自己微信号，但当真正爬取时提示更新key，但key已经更新，这是否意味着被封ip或者什么？那被封的时长是多久

**Comment by wnma3mz** [comment]
请检查正常打开文章能否看到阅读点赞等数据，如果不能则表示被封。请仔细阅读README文件，另一个可能是因为不同公众号需要更换不同的key

被封时长均在README中有说明

![image](https://user-images.githubusercontent.com/23001152/94161618-734bb380-feb8-11ea-8539-cd13dd52b219.png)

**Comment by xinghe98** [comment]
已解决

**Comment by uvlover** [comment]
我目前也显示这个，换其他微信登陆之后则可以正常爬取。应该是号被封了，请问有什么解决办法吗

**Comment by wnma3mz** [comment]
暂时无解，在README中已做相关说明

<img width="578" alt="image" src="https://user-images.githubusercontent.com/23001152/231117020-c7204f0c-4ac2-4a4a-9fce-dba8d3906750.png">
