### ISSUE TITLE
使用Pycharm 2019专业版时出现的问题

### ISSUE THREAD

**Issue by Joenothing-lst** [wnma3mz/wechat_articles_spider#35]
`ArticlesUrls` 的 `__save_login_qrcode` 并不会因为打开图片而暂停，这样会导致程序反复尝试重新登录并且打开一个新的二维码...
目前想到的解决方法是使用 `OpenCV` 的 `cvWaitKey` 方法来暂停，或者将 `__login_official` 方法最后调用的 `__startlogin_official` 方法改为自调用，并加入休眠时间。
最后说一句，大佬NB！

**Comment by wnma3mz** [comment]
感谢回复~

目前扫码登录已经放弃了~。。。。
