### ISSUE TITLE
谁能解释下，具体怎么操作？

### ISSUE THREAD

**Issue by qq596670409** [wnma3mz/wechat_articles_spider#38]

**Comment by githubtaotao** [comment]
以第一个demo为例子 test_WechatInfo.py
第一步：去fiddler的官网下载 fiddler抓包软件（https://www.telerik.com/download/fiddler-everywhere）
第二步：配置你的fiddler。让其可以抓取https、筛选url（https://blog.csdn.net/qq_35704550/article/details/91048514）
第三步：登录PC微信客户端，通过**微信客户端自带的浏览器**打开任意一篇公众号的文章。（检查下设置->通用设置->"使用系统默认浏览器打开网页" ，这里如果勾上，就去掉。如果是用系统默认的浏览器打开公众号，比如chrome浏览器打开的文章，就没办法获取到token参数）
第四步：如果上述步骤都正确，应该可以在fiddler里看到这个url： **https://mp.weixin.qq.com/mp/getappmsgext**。
然后点开这个链接。fiddler右侧webForms选项里有appmsg_token 参数的值，点raw选项可以找到cookie参数的值。 将这两个值带入test_WechatInfo.py文件，就能抓取到数据。

**Comment by ash3T** [comment]
> 以第一个demo为例子 test_WechatInfo.py 第一步：去fiddler的官网下载 fiddler抓包软件（[https://www.telerik.com/download/fiddler-everywhere）](https://www.telerik.com/download/fiddler-everywhere%EF%BC%89) 第二步：配置你的fiddler。让其可以抓取https、筛选url（[https://blog.csdn.net/qq_35704550/article/details/91048514）](https://blog.csdn.net/qq_35704550/article/details/91048514%EF%BC%89) 第三步：登录PC微信客户端，通过**微信客户端自带的浏览器**打开任意一篇公众号的文章。（检查下设置->通用设置->"使用系统默认浏览器打开网页" ，这里如果勾上，就去掉。如果是用系统默认的浏览器打开公众号，比如chrome浏览器打开的文章，就没办法获取到token参数） 第四步：如果上述步骤都正确，应该可以在fiddler里看到这个url： **[https://mp.weixin.qq.com/mp/getappmsgext**。](https://mp.weixin.qq.com/mp/getappmsgext**%E3%80%82) 然后点开这个链接。fiddler右侧webForms选项里有appmsg_token 参数的值，点raw选项可以找到cookie参数的值。 将这两个值带入test_WechatInfo.py文件，就能抓取到数据。

我试过之后，报错是：
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by 17812138923** [comment]
why my appmsg_token is na
