### ISSUE TITLE
 get info error, please check your cookie and appmsg_token

### ISSUE THREAD

**Issue by Sample-design-alt** [wnma3mz/wechat_articles_spider#42]
你好，我尝试了一下你的第一个demo，但我不知道是哪儿出了错误，一直提示 get info error, please check your cookie and appmsg_token。是我哪儿错了吗
![image](https://user-images.githubusercontent.com/66257621/131209515-8e3b3108-eb64-4f5f-8d3d-eb746bcc7c17.png)
![image](https://user-images.githubusercontent.com/66257621/131209531-d4b596a8-8c40-4b5d-b735-1a2427fe6474.png)

**Comment by wnma3mz** [comment]
运行的是哪个文件？

**Comment by Sample-design-alt** [comment]
test_WechatInfo

**Comment by wnma3mz** [comment]
请检查是否有如下可能，根据你图片框出的参数应该是没有问题的

![image](https://user-images.githubusercontent.com/23001152/131210682-27604e01-e9c8-45be-9c5b-f462402be0b8.png)

**Comment by zoucao** [comment]
遇到了同样的情况，查找文章点赞数，但是返回的content里面没有点赞相关数据
![image](https://user-images.githubusercontent.com/32817398/132131292-347c245c-5fa8-4ee6-86f8-365111b2a36a.png)

**Comment by zoucao** [comment]
> 遇到了同样的情况，查找文章点赞数，但是返回的content里面没有点赞相关数据
> ![image](https://user-images.githubusercontent.com/32817398/132131292-347c245c-5fa8-4ee6-86f8-365111b2a36a.png)
已解决：
cookie不对，爬取前没有访问过想爬取文章所在公众号，所以拿不到文章阅读量
