### ISSUE TITLE
请求get_history_url 返回结果“unknown error”

### ISSUE THREAD

**Issue by askintution** [wnma3mz/wechat_articles_spider#46]
请求get_history_url几千条之后，报错
{'ret': -6, 'errmsg': 'unknown error', 'home_page_list': []}
过了24小时也没解封，是不是封的时间现在变长了。get_history_url能否改变一下策略，一天最多爬取次数限制之类的

**Comment by wnma3mz** [comment]
你好，为啥要删掉。。问题描述。。我觉得说的挺好的。。我重新贴一下吧。。.

```
请求get_history_url几千条之后，报错
{'ret': -6, 'errmsg': 'unknown error', 'home_page_list': []}
过了24小时也没解封，是不是封的时间现在变长了。get_history_url能否改变一下策略，一天最多爬取次数限制之类的
```

最近没怎么关注了，两个点
1. 24小时是准点吗？比如8:00被封，第二天8:01还是不能抓吗？我之前的经验是24小时准点解封。。还没遇过不行的。不排除你说的情况
2. 限制策略这个，不好定其实，是有一个max参数来着。。但没写死。。因为我自己看的好像每个号每天都没固定？就有多有少，没做过定量的分析。。一般就是抓完为止，，第二天再说。。因为就算离上限还差一次请求，他好像一次都是保存的，24小时内也只能再请求1次（大概是这样）
