### ISSUE TITLE
关于参数key如何获取

### ISSUE THREAD

**Issue by tomhans2** [wnma3mz/wechat_articles_spider#58]
请问有大佬能帮忙指引一下，参数key如何获取吗，我的charles抓包好像也不正确，因为提示我需要在app内打开，我以为这个777是key，应该不能用，请大佬指点指点
<img width="975" alt="image" src="https://github.com/user-attachments/assets/c3b9bdb1-dc74-4d65-b75e-d64dae85d16e">

<img width="975" alt="image" src="https://github.com/user-attachments/assets/f1f2f6d9-a836-4939-b320-7bef18fde7c0">

**Comment by ChoHan-Soc** [comment]
请问解决了吗
