### ISSUE TITLE
点赞量与阅读量无法获取

### ISSUE THREAD

**Issue by GreenScarf** [wnma3mz/wechat_articles_spider#9]
首先感谢作者的思路和代码
但是目前的获取点赞量与阅读量的接口好像和代码中的不一样，代码中为：
appmsgext_url = origin_url + "__biz={}&mid={}&sn={}&idx={}&appmsg_token={}&x5=1".format(
            biz, mid, sn, idx, self.appmsg_token)
而我通过抓包得到getappmsgext?f=json&mock=&uin=NjY0NzM2Njgw&key...

另外，好像并不是appmsg_token 正确就有效的，具体的机制我也没分析出来，还请作者解答

**Comment by wnma3mz** [comment]
目前，我看到的有些文章好像抓取接口不大一样，所以可能会抓取失败。暂时没有不知道问题，能提供一下具体公众号吗？

**Comment by GreenScarf** [comment]
貌似跟公众号没关系，我任意点开了公众号，fildder抓包如下
![image](https://user-images.githubusercontent.com/34444225/50039481-35c4c000-006e-11e9-8a57-32b474d9b26e.png)
![image](https://user-images.githubusercontent.com/34444225/50039487-512fcb00-006e-11e9-8169-121b4cd2fda0.png)
新的接口把biz，sn，idx，mid等参数放在了body中进行post请求，并没有在url中暴露

**Comment by wnma3mz** [comment]
你可能理解错了，最后一行表示的其实就是params，并不是放到body里面去请求。
我之前可能理解错了你的第一个问题，现在重新回答一下。根据你抓包的结果，会发现post的这个url比较长，或者说在requests里面params参数需要添加很多信息。但经过实践发现，并不是所有的参数都是必须的，最后筛选的结果是代码中那几个参数。至于说为什么不使用params的方法，而直接采用字符串拼接的方法，是因为在测试的时候发现params方法有时候可能会采集失败（当然也可能是其他因素），所以最后用了字符串拼接这个url

**Comment by wnma3mz** [comment]
简而言之，抓包获取的很多参数并不是必须的。关于你说的“好像并不是appmsg_token 正确就有效的”，我没有理解到你的意思？appmsg_token是个人微信登录时微信给的一个token，具有时效性，所以可能会在一段时间内发生变化。比如，你在某时刻用fiddler抓包看到appmsg_token之后，运行爬虫，之后再去运行fiddler抓包看到appmsg_token是不一样的

**Comment by GreenScarf** [comment]
谢谢码主解答，我理解你的意思。
因为我发现key这个参数貌似很起作用，即便token是对的，但是key错了，服务器返回了如下结果
![image](https://user-images.githubusercontent.com/34444225/50039666-c6040480-0070-11e9-9ba5-85677eec3f28.png)
其中并没有appmsgstat
所以我说并不是token正确就能获取到点赞量。
但是从码主的代码来看，没有传入key这个参数。

因为我之前跑码主代码也是得到图中的结果，所以我才以为是接口不对，我再研究研究，谢谢码主！
